USE INTEGRITY_TEST;

LOAD DATA LOCAL INFILE "C:/repos/data-mapping/output/data/LOOPS.CSV"
INTO TABLE LOOPS
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;

SHOW WARNINGS;

LOAD DATA LOCAL INFILE "C:/repos/data-mapping/output/data/EQUIPMENT.CSV"
INTO TABLE EQUIPMENT
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;

SHOW WARNINGS;

LOAD DATA LOCAL INFILE "C:/repos/data-mapping/output/data/DAMAGE_MECHANISM.CSV"
INTO TABLE DAMAGE_MECHANISM
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;

SHOW WARNINGS;

LOAD DATA LOCAL INFILE "C:/repos/data-mapping/output/data/STRATEGY.CSV"
INTO TABLE STRATEGY
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;

SHOW WARNINGS;

LOAD DATA LOCAL INFILE "C:/repos/data-mapping/output/data/CML.CSV"
INTO TABLE CML
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;

SHOW WARNINGS;

LOAD DATA LOCAL INFILE "C:/repos/data-mapping/output/data/INSPECTION.CSV"
INTO TABLE INSPECTION
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;

SHOW WARNINGS;

LOAD DATA LOCAL INFILE "C:/repos/data-mapping/output/data/GRID.CSV"
INTO TABLE GRID
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES;

SHOW WARNINGS;
